# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Programs
    url: academic-programs
    weight: 30
    hasChildren: true
  - name: Programs Overview
    url: academic-programs
    parent: Programs
    weight: 31
  - name: Undergraduate Degrees
    url: academic-programs/undergraduate-degrees
    parent: Programs
    weight: 32
  - name: Graduate Degrees
    url: academic-programs/graduate-degrees
    parent: Programs
    weight: 33
  - name: Graduate Certificates
    url: academic-programs/graduate-certificates
    parent: Programs
    weight: 34
  - name: Themes
    url: academic-themes
    weight: 40
    hasChildren: true
  - name: Themes Overview
    url: academic-themes
    parent: Themes
    weight: 41
  - name: Sustainability
    url: academic-themes/sustainability
    parent: Themes
    weight: 42
  - name: Parks and Leisure
    url: academic-themes/parks-and-leisure
    parent: Themes
    weight: 43
  - name: Urban Planning
    url: academic-themes/urban-planning
    parent: Themes
    weight: 44
  - name: Geographic Informatin Science
    url: academic-themes/gis
    parent: Themes
    weight: 45
  - name: Outdoor Education and Leadership
    url: academic-themes/outdoor-education
    parent: Themes
    weight: 46
  - name: Public Safety and Law Enforcement
    url: academic-themes/law-enforcement
    parent: Themes
    weight: 47
  # - name: Research Highlights
  #   url: highlights
  #   weight: 45
  - name: People
    url: faculty-profiles
    weight: 50
  - name: Alumni
    url: alumni
    weight: 60
