# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: People
    url: faculty-profiles
    weight: 15
  - name: Academic Programs
    url: academic-programs
    weight: 20
    hasChildren: true
  - name: Overview
    url: academic-programs
    parent: Academic Programs
    weight: 20
  - name: Undergraduate Degrees
    url: academic-programs/undergraduate-degrees
    parent: Academic Programs
    weight: 21
  - name: Graduate Degrees
    url: academic-programs/graduate-degrees
    parent: Academic Programs
    weight: 22
  - name: Graduate Certificates
    url: academic-programs/graduate-certificates
    parent: Academic Programs
    weight: 23
  - name: Research
    url: research
    weight: 20
    hasChildren: true
  - name: Research Impact
    url: research
    parent: Research
    weight: 30
  - name: Research Themes
    url: research-themes
    parent: Research
    weight: 31
  - name: Faculty Research
    url: faculty
    parent: Research
    weight: 32
  - name: Student Research
    url: students
    parent: Research
    weight: 33
  - name: Analytics
    url: analytics
    parent: Research
    weight: 34
  - name: About
    url: about
    parent: Research
    weight: 35
  # - name: Research Highlights
  #   url: highlights
  #   weight: 45
  - name: Alumni
    url: alumni
    weight: 50
